#version 450

#include "dequant_head.glsl"
#include "turbo.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {block_turbo4_0 data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

void main() {
    const uint i = gl_WorkGroupID.x * 4 + gl_LocalInvocationID.x / 64;

    const uint tid = gl_LocalInvocationID.x % 64;
    const uint il  = tid / 4;
    const uint ir  = tid % 4;
    const uint ib = 4*i + ir;
    if (ib >= p.nel / 128) {
        return;
    }

    const uint b_idx = 512*i + 128*ir + 8*il;

    const float norm = float(data_a[ib].norm);

    [[unroll]] for (uint l = 0; l < 8; ++l) {
        const uint e = 8*il + l;
        const uint byte = uint(data_a[ib].qs[e / 2]);
        const uint idx = ((e & 1u) != 0u) ? (byte >> 4u) : (byte & 0xFu);
        data_b[b_idx + l] = D_TYPE(norm * k_turbo_centroids_4bit[idx]);
    }
}
