#version 450

#include "dequant_head.glsl"
#include "turbo.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer A {block_turbo2_0 data_a[];};
layout (binding = 1) writeonly buffer D {D_TYPE data_b[];};

void main() {
    const uint i = gl_WorkGroupID.x * 4 + gl_LocalInvocationID.x / 64;

    const uint tid = gl_LocalInvocationID.x % 64;
    const uint il  = tid / 32;
    const uint ir  = tid % 32;
    const uint ib = 32*i + ir;
    if (ib >= p.nel / 32) {
        return;
    }

    const uint b_idx = 1024*i + 32*ir + 16*il;

    const float norm = float(data_a[ib].norm);

    [[unroll]] for (uint l = 0; l < 16; ++l) {
        const uint e = 16*il + l;
        const uint idx = (uint(data_a[ib].qs[e / 4u]) >> (2u * (e % 4u))) & 0x3u;
        data_b[b_idx + l] = D_TYPE(norm * k_turbo_centroids_2bit[idx]);
    }
}
